# Generated by Django 3.0.6 on 2020-05-19 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Planet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planet_name', models.CharField(max_length=50, verbose_name='Название Планеты')),
            ],
        ),
        migrations.CreateModel(
            name='Quest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quest_id', models.CharField(max_length=250, verbose_name='Уникальный код Ордена')),
                ('quest_list', models.CharField(max_length=50, verbose_name='Список вопроов')),
            ],
        ),
        migrations.CreateModel(
            name='Recrut',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recrut_Name', models.CharField(max_length=50, verbose_name='Имя Рекрута')),
                ('recrut_Planet', models.CharField(max_length=50, verbose_name='Планета обитания')),
                ('recrut_Age', models.CharField(max_length=50, verbose_name='Возраст')),
                ('recrut_Email', models.EmailField(max_length=254, verbose_name='Email')),
            ],
        ),
        migrations.CreateModel(
            name='Sith',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sith_Name', models.CharField(max_length=50, verbose_name='Имя Ситха')),
                ('sith_Planet', models.CharField(max_length=50, verbose_name='Планета обучения')),
            ],
        ),
    ]
