# Generated by Django 3.0.6 on 2020-05-21 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servisrecruting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test_of_shadow_hand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_of_shadow_hand_id', models.CharField(max_length=250, verbose_name='Уникальный код Ордена')),
                ('test_of_shadow_hand_list', models.TextField(max_length=200000, verbose_name='Список вопроов')),
            ],
            options={
                'verbose_name': 'Испытание Руки Тени',
                'verbose_name_plural': 'Испытания Руки Тени',
            },
        ),
        migrations.DeleteModel(
            name='Quest',
        ),
        migrations.AlterModelOptions(
            name='planet',
            options={'verbose_name': 'Планета', 'verbose_name_plural': 'Планеты'},
        ),
        migrations.AlterModelOptions(
            name='sith',
            options={'verbose_name': 'Ситх', 'verbose_name_plural': 'Ситхи'},
        ),
    ]
