# Generated by Django 3.0.6 on 2020-08-18 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servisrecruting', '0003_auto_20200627_1702'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recrut',
            old_name='recrut_Age',
            new_name='recrut_age',
        ),
        migrations.RenameField(
            model_name='recrut',
            old_name='recrut_Email',
            new_name='recrut_email',
        ),
        migrations.RenameField(
            model_name='recrut',
            old_name='recrut_Name',
            new_name='recrut_name',
        ),
        migrations.RenameField(
            model_name='recrut',
            old_name='recrut_Planet',
            new_name='recrut_planet',
        ),
        migrations.RenameField(
            model_name='sith',
            old_name='sith_Name',
            new_name='sith_name',
        ),
        migrations.RenameField(
            model_name='sith',
            old_name='sith_Planet',
            new_name='sith_planet',
        ),
    ]
