# Generated by Django 3.0.6 on 2020-08-18 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servisrecruting', '0004_auto_20200818_1539'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sith',
            name='planet',
        ),
        migrations.AddField(
            model_name='planet',
            name='recruts_in_mtm',
            field=models.ManyToManyField(related_name='recruts', to='servisrecruting.Recrut'),
        ),
        migrations.AddField(
            model_name='planet',
            name='siths_in_mtm',
            field=models.ManyToManyField(related_name='planets', to='servisrecruting.Sith'),
        ),
    ]
