# Generated by Django 3.0.6 on 2020-08-18 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servisrecruting', '0005_auto_20200818_1937'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recrut',
            name='recrut',
        ),
    ]
